/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a user account
         * @description Creates a new user account. Does not log the caller in — call POST /auth/login afterwards to obtain a session token.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in and obtain a session token
         * @description Verifies email/password and issues a new bearer session token, valid for AUTH_SESSION_TTL (default 24h). The raw token is returned exactly once, in this response — it cannot be recovered later; only its hash is stored server-side. Send it back as `Authorization: Bearer <token>` on every subsequent request to a protected endpoint.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/csrf-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtain a CSRF token
         * @description Returns the CSRF token this client must send back in the X-CSRF-Token header on every state-changing request (POST, PUT, PATCH, DELETE) that does not carry Authorization: Bearer — this includes POST /auth/login and POST /auth/register, not only already-authenticated routes. See docs/DECISIONS.md § "Autenticação: modo duplo (cookie httpOnly + Bearer)" for why: a request without Authorization is assumed to come from a browser, and a browser's cookie-carried session is exactly what CSRF protects.
         *
         *     Public — a caller has no session the first time it needs this token. Calling it also sets (or refreshes) the underlying CSRF cookie, which is HttpOnly and never readable by JavaScript; only this endpoint's response body ever exposes the token value itself.
         */
        get: operations["getCsrfToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invalidate the current session token
         * @description Deletes the session backing the bearer token used for this request.
         *     Repeating it with the *same* token returns 401, not 204: the endpoint requires authentication, and the first call already destroyed the session that authenticates it. The idempotency here is server-side — deleting an already-absent session is not treated as an error internally — but it is not observable through this endpoint, because a request carrying an unknown or expired token is rejected before it reaches the handler. Clients should treat both 204 and 401 as "the session is gone", which is the outcome logout is asking for either way.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invalidate every session belonging to the caller
         * @description Deletes every session for the authenticated account — including the one that authenticated this very request. Meant for a caller who suspects a token of theirs has leaked: one call guarantees every live session is gone, the active one included, rather than needing to know which token to target individually.
         *
         *     This is the deliberate counterpart to the per-account session cap (see `docs/DECISIONS.md` § "Limite de sessões: teto com evicção da mais antiga"): the cap evicts a user's oldest session automatically once a new login exceeds it, but that is a passive mechanism that only helps if the account keeps logging in normally elsewhere. A caller who wants every session gone *right now* — including a suspected leak — uses this endpoint instead.
         */
        post: operations["logoutAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the authenticated user */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the authenticated caller's tasks
         * @description Returns the authenticated caller's own tasks — never another user's — ordered by `created_at` ascending (oldest first; ties broken by `id`). The Repository guarantees this ordering and applies the ownership filter and `limit`/`offset` itself (pushed into the SQL query for the PostgreSQL-backed store: `WHERE user_id = … ORDER BY … LIMIT … OFFSET …`), rather than the Service fetching everything and filtering/paginating in memory. `limit` and `offset` are optional; omitting both returns every task the caller owns. Returns an empty JSON array, never `null`, when the caller has no tasks or when `offset` is past the end of the list.
         */
        get: operations["listTasks"];
        put?: never;
        /**
         * Create a task
         * @description Creates a new task owned by the authenticated caller, with status `pending`. `id`, `status`, `created_at` and `updated_at` are always assigned by the server; if the client includes any of these fields in the request body, or any other field not part of CreateTaskRequest, they are silently ignored — the API never returns a 400 for unknown fields.
         */
        post: operations["createTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one of the authenticated caller's tasks by id */
        get: operations["getTask"];
        /**
         * Update a task's title, description and/or priority
         * @description Replaces `title` and `description`, and — if `priority` is present and non-empty — `priority` too; an omitted or empty `priority` leaves it unchanged. `id`, `status` and `created_at` are never modified by this endpoint — to change `status`, use PATCH /tasks/{id}/status (or PATCH /tasks/{id}/done). As with creation, any field in the body other than `title`/`description`/`priority` (e.g. a client-supplied `status` or `id`) is silently ignored. `updated_at` is always refreshed to the current time.
         */
        put: operations["updateTask"];
        post?: never;
        /**
         * Delete a task
         * @description Permanently removes a task. No request body.
         */
        delete: operations["deleteTask"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tasks/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Move a task to a different status
         * @description Moves the task to `status`, if that's a legal transition from its current status — see the Status schema's transition table. Requesting the task's *current* status again always succeeds as a no-op (200, `updated_at` unchanged, nothing written) — the same idempotency PATCH /tasks/{id}/done has always provided for an already-`done` task, generalized to every status.
         */
        patch: operations["transitionTaskStatus"];
        trace?: never;
    };
    "/v1/tasks/{id}/done": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Mark a task as done
         * @description Marks the task `done`. No request body is read by this endpoint — any body sent is ignored. A thin, backward-compatible convenience wrapper around PATCH /tasks/{id}/status with `{"status":"done"}` — kept as its own endpoint because it predates the general one and its wire contract must not change.
         *
         *     This operation is **idempotent**: calling it on a task that is already `done` returns 200 with the task unchanged, and does *not* refresh `updated_at` or write to the repository.
         *     It is *not* a universal shortcut: it applies the same transition rules as PATCH /tasks/{id}/status, so it only succeeds from a status that can legally reach `done` — `pending` and `in_progress`. A `cancelled` task cannot be completed in one hop (see the Status schema's transition table) and returns 409; move it back to `pending` first.
         */
        patch: operations["completeTask"];
        trace?: never;
    };
    "/v1/tasks/{id}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Server-generated task identifier (a UUIDv4 as produced by CreateTask), scoped to the authenticated caller.
                 *     A well-formed but unknown id, a well-formed id belonging to a *different* user, and a **malformed** id (not a syntactically valid UUID) all result in 404, identically. `Service.isValidID` rejects a malformed shape before either storage backend is consulted (`internal/task/service.go`), which is what makes the in-memory and PostgreSQL-backed stores agree — PostgreSQL's own `::uuid` cast would otherwise reject the value as a query error (500) rather than as "no rows", a divergence `TestPostgres_FindByID_MalformedID` still documents for a caller that reaches `Repository` directly, bypassing `Service`. The API never reveals, through the status code alone, which of the three cases applies — that is what keeps a non-owner from learning whether a given task ID exists.
                 * @example f47ac10b-58cc-4372-a567-0e02b2c3d479
                 */
                id: components["parameters"]["TaskID"];
            };
            cookie?: never;
        };
        /**
         * List a task's attachments
         * @description Ordered oldest first, ties broken by id. Returns `[]` for a task of yours with no attachments, and 404 for a task that is not yours — the two are distinguishable only to the owner.
         */
        get: operations["listAttachments"];
        put?: never;
        /**
         * Upload a file attachment to a task
         * @description Accepts one file in a `multipart/form-data` body, under the part name `file`. Any other part is ignored.
         *
         *     The content type is determined from the bytes themselves, not from the part's declared `Content-Type`: a client writes that header and can put anything in it, so trusting it would make the allow-list decorative. The detected type is what is stored and what a later download reports. Accepted types are `image/jpeg`, `image/png`, `image/gif`, `image/webp`, `application/pdf` and `text/plain`; anything else is rejected with 400, including HTML, which is excluded deliberately.
         *
         *     The client's filename is kept as metadata only and is never used to build a path — the file is stored under a server-generated `storage_key`. The size limit (`ATTACHMENT_MAX_BYTES`, 10 MiB by default) is enforced while streaming, not read from `Content-Length`.
         *
         *     The caller's total across every attachment they own — `ATTACHMENT_MAX_BYTES_PER_USER`, 500 MiB by default — is checked *before* the upload streams in, using the total the caller already had. A caller already at or over the quota is refused without a single byte being read; one accepted upload can push the total up to `ATTACHMENT_MAX_BYTES` past the quota (see `docs/DECISIONS.md` § "Quota de anexos" for why that overshoot is accepted).
         *
         *     These routes exist only when `ATTACHMENT_STORAGE_DIR` is configured; otherwise every one of them returns 404.
         */
        post: operations["uploadAttachment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/files/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download an attachment's contents
         * @description Addressed by `storage_key`, which is not a capability: holding one grants nothing on its own, because the key is resolved to its attachment and the owning task's ownership is re-checked before any bytes are served. A key belonging to another user is answered exactly like a key that names nothing.
         *
         *     The response carries `Content-Disposition: attachment` so a browser saves the file rather than rendering user-supplied bytes in this API's origin, and `X-Content-Type-Options: nosniff` (set on every response) so it does not re-decide the type for itself. Range requests are supported.
         */
        get: operations["downloadAttachment"];
        put?: never;
        post?: never;
        /**
         * Delete an attachment
         * @description Removes both the metadata row and the underlying file, in the same request — not deferred to the orphan collector's own schedule. See docs/DECISIONS.md § "Delete de anexo: síncrono, não só o coletor" for the full reasoning, including why a second delete of the same key returns 404 rather than a silent 204.
         *
         *     Ownership follows the same rule as download: a key belonging to another user's task is answered exactly like a key that names nothing. No request body.
         */
        delete: operations["deleteAttachment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/debug/vars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Runtime statistics (expvar)
         * @description The Go standard library's `expvar` handler: the process command line and full runtime/GC statistics (`memstats`, allocation counters, and any other published variables) as JSON. Baseline operational visibility with no external metrics dependency.
         *     Unlike GET /health and GET /health/ready, this endpoint **requires authentication** — it exposes internal runtime detail and fingerprints the deployment, and unlike an orchestrator's probe (which has no credentials to present), whoever reads these numbers can carry a token.
         *     The response shape is defined by `expvar`, not by this API: it is an open-ended JSON object whose keys depend on what the runtime and the process publish, so it is intentionally not modelled as a fixed schema here.
         *     When `CRIER_OTLP_ENDPOINT` is configured, two additional keys appear: `crier_buffer_depth` (records buffered and not yet exported) and `crier_records_dropped` (a JSON object counting records lost, by reason). Both report zero/empty when crier is not configured — see docs/DECISIONS.md's Fase 11 section.
         */
        get: operations["getDebugVars"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness check
         * @description Always responds 200 while the process is running. Does not check PostgreSQL or any other dependency — use GET /health/ready for that. Intended for a process supervisor / container runtime liveness probe (restart the process if this stops responding).
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness check
         * @description Reports whether the database is actually reachable, not just whether the process is alive. For the in-memory store (no DATABASE_URL configured) this always reports ready, since there is nothing external to check. For PostgreSQL, it pings the shared connection pool (used by both the task and user repositories) with a 5s timeout. Intended for a load balancer / Kubernetes readiness probe, so traffic stops routing to a replica whose database connection is broken.
         */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Body returned by both GET /health and GET /health/ready. */
        HealthResponse: {
            /** @enum {string} */
            status: "ok" | "unavailable";
        };
        /** @description The persisted representation of a user account. Never includes a password or password hash — user.User.PasswordHash is `json:"-"` and is never serialized to any response. */
        User: {
            /**
             * Format: uuid
             * @example 9f8e7d6c-5b4a-3210-9876-543210fedcba
             */
            readonly id: string;
            /**
             * Format: email
             * @example alice@example.com
             */
            email: string;
            /**
             * Format: date-time
             * @example 2026-08-08T12:00:00Z
             */
            readonly created_at: string;
            /**
             * Format: date-time
             * @example 2026-08-08T12:00:00Z
             */
            readonly updated_at: string;
        };
        /** @description The body returned by GET /v1/auth/me: every User field, plus attachments_enabled. That field is not part of User itself — User is also RegisterResponse's schema, and whether attachment upload/download routes exist at all is a deployment-wide configuration fact (see config.Config.AttachmentStorageDir / ATTACHMENT_S3_ENDPOINT), not something about a particular account. A frontend reads it to decide whether to offer attachment UI, instead of inferring availability from a 404 that could also mean something else. */
        MeResponse: components["schemas"]["User"] & {
            /** @example true */
            readonly attachments_enabled: boolean;
        };
        /** @description Accepted body for POST /auth/register. */
        RegisterRequest: {
            /**
             * Format: email
             * @description Required. Must contain "@". Trimmed of leading/trailing whitespace.
             * @example alice@example.com
             */
            email: string;
            /**
             * @description Required, 8–72 characters. The 72-character ceiling is bcrypt's own input limit (golang.org/x/crypto/bcrypt rejects longer input outright), not an arbitrary policy choice.
             * @example correct horse battery staple
             */
            password: string;
        };
        /** @description Accepted body for POST /auth/login. */
        LoginRequest: {
            /**
             * Format: email
             * @example alice@example.com
             */
            email: string;
            /** @example correct horse battery staple */
            password: string;
        };
        /** @description Body returned by a successful POST /auth/login. */
        LoginResponse: {
            /**
             * @description Bearer session token. Returned exactly once — only its hash is stored server-side, so it cannot be retrieved again after this response.
             * @example 0094162c1a4c9c2e5aa5897e55ea477e6dd089a60e2d060303c82ff1fe82e6d
             */
            token: string;
            /**
             * Format: date-time
             * @description When `token` stops being valid (see AUTH_SESSION_TTL).
             * @example 2026-08-09T12:00:00Z
             */
            expires_at: string;
            user: components["schemas"]["User"];
        };
        /** @description Body returned by GET /auth/csrf-token. */
        CsrfTokenResponse: {
            /**
             * @description Send back in the X-CSRF-Token header on every state-changing request that does not carry Authorization: Bearer — see GET /auth/csrf-token's own description for exactly when that applies.
             * @example 3f9c2b1a7e6d4c8b0f1a2e3d4c5b6a7f8e9d0c1b2a3f4e5d6c7b8a9f0e1d2c3b
             */
            csrf_token: string;
        };
        /**
         * @description Task lifecycle state. Legal transitions (enforced by Service, not just this enum — a database CHECK constraint only fences the value set):
         *
         *     ```
         *     from \ to     pending  in_progress  done  cancelled
         *     pending          -          Y        Y        Y
         *     in_progress      Y          -        Y        Y
         *     done             Y          Y        -        N
         *     cancelled        Y          N        N        -
         *     ```
         *
         *     Requesting the task's current status again always succeeds as a no-op, independent of this table. `done` and `cancelled` are both reopenable back to `pending` (and `done` can resume directly to `in_progress`), but a `cancelled` task must pass back through `pending` before becoming active again.
         * @enum {string}
         */
        Status: "pending" | "in_progress" | "done" | "cancelled";
        /**
         * @description How urgently a task should be worked on. No transition rules — settable to any value at any time.
         * @enum {string}
         */
        Priority: "low" | "medium" | "high";
        /** @description The persisted representation of a task, as returned by every endpoint that returns a task body. Field order and JSON keys match the `json` struct tags on task.Task exactly (snake_case). The owning user's id is deliberately not included — every task a client can ever retrieve already belongs to it. */
        Task: {
            /**
             * Format: uuid
             * @description Server-generated UUIDv4. Never accepted from the client.
             * @example f47ac10b-58cc-4372-a567-0e02b2c3d479
             */
            readonly id: string;
            /** @example Buy groceries */
            title: string;
            /** @example Milk, eggs, bread */
            description: string;
            status: components["schemas"]["Status"];
            priority: components["schemas"]["Priority"];
            /**
             * Format: date-time
             * @description Set once at creation; never modified afterwards.
             * @example 2026-08-08T12:00:00Z
             */
            readonly created_at: string;
            /**
             * Format: date-time
             * @description Refreshed on every mutation that actually changes something (PUT, and every status transition that isn't a same-status no-op). Left unchanged by an idempotent PATCH .../done or PATCH .../status call.
             * @example 2026-08-08T12:00:00Z
             */
            readonly updated_at: string;
        };
        /** @description Accepted body for POST /tasks. Any additional field beyond `title`/`description`/`priority` is silently ignored by the server rather than rejected. `title`/`description` are trimmed of leading/trailing whitespace before being stored (length limits below are checked after trimming). */
        CreateTaskRequest: {
            /**
             * @description Required. Rejected with 400 if empty or made of only whitespace after trimming, or if longer than 200 characters.
             * @example Buy groceries
             */
            title: string;
            /**
             * @description Optional. Defaults to an empty string if omitted. Rejected with 400 if longer than 2000 characters.
             * @example Milk, eggs, bread
             */
            description?: string;
            /**
             * @description Optional. Defaults to `medium` when omitted **or** sent as an empty string — the server treats "" as "not provided" rather than rejecting it, which is why "" appears in this enum even though it is not a valid stored Priority value.
             * @example high
             * @enum {string}
             */
            priority?: "low" | "medium" | "high" | "";
        };
        /** @description Accepted body for PUT /tasks/{id}. Same title/description validation as CreateTaskRequest; any additional field (including `status` or `id`) is silently ignored. */
        UpdateTaskRequest: {
            /**
             * @description Required. Rejected with 400 if empty or made of only whitespace after trimming, or if longer than 200 characters.
             * @example Buy groceries and cook dinner
             */
            title: string;
            /**
             * @description Optional. Defaults to an empty string if omitted. Rejected with 400 if longer than 2000 characters.
             * @example Don't forget olive oil
             */
            description?: string;
            /**
             * @description Optional. Omitted **or** sent as an empty string leaves the task's current priority unchanged — "" is the server's "not provided" sentinel, which is why it appears in this enum even though it is not a valid stored Priority value.
             * @example high
             * @enum {string}
             */
            priority?: "low" | "medium" | "high" | "";
        };
        /** @description Accepted body for PATCH /tasks/{id}/status. */
        TransitionStatusRequest: {
            status: components["schemas"]["Status"];
        };
        /** @description Metadata about one file stored against a task. The bytes themselves live outside the database, addressed by `storage_key`. */
        Attachment: {
            /**
             * Format: uuid
             * @description The attachment's own identifier.
             */
            id: string;
            /**
             * Format: uuid
             * @description The task this file hangs off. The attachment has no owner of its own — ownership is reached through this task.
             */
            task_id: string;
            /**
             * @description What the client called the file, normalized (control characters stripped, whitespace collapsed, any directory part removed). Metadata only: it is never used to build a path, and the file on disk is named by `storage_key`.
             * @example report.pdf
             */
            original_filename: string;
            /**
             * Format: uuid
             * @description The identifier `GET /files/{key}` addresses this file by. Server-generated and never derived from client input, which is what makes it unable to carry a traversal sequence. It is not a capability: a download still re-checks that the caller owns the task behind it.
             */
            storage_key: string;
            /**
             * @description The type detected from the bytes, not the one the upload declared.
             * @example application/pdf
             */
            content_type: string;
            /**
             * Format: int64
             * @description The stored size, as measured while writing.
             * @example 20841
             */
            size_bytes: number;
            /** Format: date-time */
            created_at: string;
        };
        /** @description The single JSON envelope used by every error response from every endpoint in this API. */
        ErrorResponse: {
            /**
             * @description Human-readable error message. Never contains internal details.
             * @example task not found
             */
            error: string;
        };
    };
    responses: {
        /** @description Missing, malformed, or invalid/expired `Authorization: Bearer` header. */
        Unauthorized: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestID"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "invalid or expired session token"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /**
         * @description CSRF verification failed on a state-changing request that did not carry `Authorization: Bearer` (see the `cookieAuth` security scheme and docs/DECISIONS.md § "Autenticação: modo duplo"). Concretely, one of: the request has no `X-CSRF-Token` header; the token doesn't match the CSRF cookie; the CSRF cookie itself is missing, expired, or was never issued (call GET /v1/auth/csrf-token first); or the `Origin`/`Referer` header doesn't identify an allowed origin. The response is deliberately identical for all of these — distinguishing them would hand an attacker a progress indicator for a forged request.
         *
         *     **Unlike every other error response in this API, the body here is NOT the `{"error": "..."}` envelope.** It is the plain text `Forbidden`, with `Content-Type: text/plain`, written by `moat/csrf`'s default rejection handler — a known, intentional-for-now inconsistency; see docs/ARCHITECTURE.md § Future Improvements.
         *
         *     A request carrying `Authorization: Bearer` never sees this response — it is exempt from CSRF entirely, whatever cookies it happens to also carry.
         */
        Forbidden: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestID"];
                [name: string]: unknown;
            };
            content: {
                /** @example Forbidden */
                "text/plain": string;
            };
        };
        /**
         * @description A rate limit was exceeded. Three token-bucket tiers can produce this, and a client cannot tell them apart from the response alone: a global one keyed by client address in front of every route; a tighter one covering /auth/register and /auth/login together (where each attempt costs a password hash comparison); and one keyed by authenticated user on every route requiring a token, so an account cannot multiply its allowance across hosts. All are configurable — see RATE_LIMIT_*, AUTH_RATE_LIMIT_* and USER_RATE_LIMIT_* in .env.example.
         *     The only endpoints that never return this are GET /health and GET /health/ready, which bypass rate limiting so that a burst of client traffic cannot be read by an orchestrator as an unhealthy replica.
         *     Wait and retry; the response carries the standard rate-limit headers describing when.
         */
        TooManyRequests: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestID"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "too many requests, please try again later"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description No task exists with the given id, or it belongs to a different user (see the `id` path parameter's description — both cases are indistinguishable on purpose). */
        NotFound: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestID"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "task not found"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description An unexpected server-side failure. The response body is always this exact generic message — the underlying error is never exposed to the client, only logged server-side (with the same X-Request-Id, for correlation). */
        InternalServerError: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestID"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "internal server error"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /**
         * @description The session lookup that authenticates this request could not be performed — the database is unreachable, timed out, or the request was canceled. **This says nothing about the caller's token:** a perfectly valid, unexpired token gets this response too, so the client must NOT discard its credentials and re-authenticate. Retry the same request with the same token once the service recovers (GET /health/ready reports when that is).
         *     Returned only by endpoints that require authentication, since it originates in the session lookup itself. POST /auth/register and POST /auth/login perform no such lookup, so the same underlying database failure surfaces there as a 500 instead.
         */
        ServiceUnavailable: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestID"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "service temporarily unavailable, please retry"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /**
         * @description Server-generated task identifier (a UUIDv4 as produced by CreateTask), scoped to the authenticated caller.
         *     A well-formed but unknown id, a well-formed id belonging to a *different* user, and a **malformed** id (not a syntactically valid UUID) all result in 404, identically. `Service.isValidID` rejects a malformed shape before either storage backend is consulted (`internal/task/service.go`), which is what makes the in-memory and PostgreSQL-backed stores agree — PostgreSQL's own `::uuid` cast would otherwise reject the value as a query error (500) rather than as "no rows", a divergence `TestPostgres_FindByID_MalformedID` still documents for a caller that reaches `Repository` directly, bypassing `Service`. The API never reveals, through the status code alone, which of the three cases applies — that is what keeps a non-owner from learning whether a given task ID exists.
         * @example f47ac10b-58cc-4372-a567-0e02b2c3d479
         */
        TaskID: string;
    };
    requestBodies: never;
    headers: {
        /**
         * @description Correlates this response with server-side structured logs (`request_id` field). Echoes the client-supplied `X-Request-Id` request header when it is present and well-formed (non-empty, at most 128 characters, and restricted to `[A-Za-z0-9_-]`); otherwise the server generates a new one. Present on every response from every endpoint, including error responses.
         * @example 7a947bb6436a2e5009efcaa55c42cdf8
         */
        XRequestID: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Request bodies larger than 1 MiB are rejected, surfacing as the same 400 "invalid request body" response as malformed JSON — the same cap the task endpoints apply. */
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "email": "alice@example.com",
                 *       "password": "correct horse battery staple"
                 *     }
                 */
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Account created. */
            201: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "9f8e7d6c-5b4a-3210-9876-543210fedcba",
                     *       "email": "alice@example.com",
                     *       "created_at": "2026-08-08T12:00:00Z",
                     *       "updated_at": "2026-08-08T12:00:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Malformed JSON body; an empty/malformed `email` (must contain "@", at most 320 characters); or a `password` shorter than 8 or longer than 72 characters (bcrypt's own input limit). */
            400: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "invalid input: password must be at least 8 characters"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            /** @description A user with this email is already registered. */
            409: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "email already registered"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Request bodies larger than 1 MiB are rejected, surfacing as the same 400 "invalid request body" response as malformed JSON. */
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "email": "alice@example.com",
                 *       "password": "correct horse battery staple"
                 *     }
                 */
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated successfully. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "token": "0094162c1a4c9c2e5aa5897e55ea477e6dd089a60e2d060303c82ff1fe82e6d",
                     *       "expires_at": "2026-08-09T12:00:00Z",
                     *       "user": {
                     *         "id": "9f8e7d6c-5b4a-3210-9876-543210fedcba",
                     *         "email": "alice@example.com",
                     *         "created_at": "2026-08-08T12:00:00Z",
                     *         "updated_at": "2026-08-08T12:00:00Z"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Malformed JSON body. */
            400: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "invalid request body"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unknown email or wrong password — deliberately the same response either way, so a caller can never distinguish "no such account" from "wrong password" and enumerate registered emails. */
            401: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "invalid email or password"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getCsrfToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A CSRF token was issued. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "csrf_token": "3f9c2b1a7e6d4c8b0f1a2e3d4c5b6a7f8e9d0c1b2a3f4e5d6c7b8a9f0e1d2c3b"
                     *     }
                     */
                    "application/json": components["schemas"]["CsrfTokenResponse"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out. No response body. */
            204: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    logoutAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every session for the account deleted. No response body. */
            204: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user identified by the bearer token used for this request. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description The token authenticated successfully but its owning user no longer exists. Only reachable if the account was removed out of band (direct SQL, `cmd/seed -reset`) between the session lookup and this read — this API exposes no endpoint that deletes a user, and deleting one normally cascades its sessions away, which would produce a 401 instead. */
            404: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "user not found"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listTasks: {
        parameters: {
            query?: {
                /**
                 * @description Maximum number of tasks to return. Sending the parameter with an empty value (`?limit=`) is treated as omitting it, not as an error.
                 * @example 20
                 */
                limit?: number;
                /**
                 * @description Number of tasks to skip before collecting `limit` results. Sending the parameter with an empty value (`?offset=`) is treated as omitting it, not as an error.
                 * @example 0
                 */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success. The array is empty (`[]`) if the caller has no tasks, or if `offset` is past the end of the list. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"][];
                };
            };
            /** @description `limit` or `offset` is present but not a non-negative integer. */
            400: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "invalid input: limit must be a non-negative integer"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    createTask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Request bodies larger than 1 MiB are rejected (surfaces as the same 400 "invalid request body" response as malformed JSON). */
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTaskRequest"];
            };
        };
        responses: {
            /** @description Task created successfully. */
            201: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "f47ac10b-58cc-4372-a567-0e02b2c3d479",
                     *       "title": "Buy groceries",
                     *       "description": "Milk, eggs, bread",
                     *       "status": "pending",
                     *       "priority": "high",
                     *       "created_at": "2026-08-08T12:00:00Z",
                     *       "updated_at": "2026-08-08T12:00:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Malformed JSON body; a missing, empty, or whitespace-only `title`; a `title`/`description` longer than 200/2000 characters (after trimming); or a `priority` that isn't one of `low`/`medium`/`high`. */
            400: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description A task with the server-generated id already exists. Practically unreachable in normal operation: `id` is a UUIDv4 generated internally by the Service and never supplied by the client, so this can only happen on an astronomically unlikely UUID collision. Documented because the code path exists and is reachable in principle, not because it is expected to occur. */
            409: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "task already exists"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Server-generated task identifier (a UUIDv4 as produced by CreateTask), scoped to the authenticated caller.
                 *     A well-formed but unknown id, a well-formed id belonging to a *different* user, and a **malformed** id (not a syntactically valid UUID) all result in 404, identically. `Service.isValidID` rejects a malformed shape before either storage backend is consulted (`internal/task/service.go`), which is what makes the in-memory and PostgreSQL-backed stores agree — PostgreSQL's own `::uuid` cast would otherwise reject the value as a query error (500) rather than as "no rows", a divergence `TestPostgres_FindByID_MalformedID` still documents for a caller that reaches `Repository` directly, bypassing `Service`. The API never reveals, through the status code alone, which of the three cases applies — that is what keeps a non-owner from learning whether a given task ID exists.
                 * @example f47ac10b-58cc-4372-a567-0e02b2c3d479
                 */
                id: components["parameters"]["TaskID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task found. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "f47ac10b-58cc-4372-a567-0e02b2c3d479",
                     *       "title": "Buy groceries",
                     *       "description": "Milk, eggs, bread",
                     *       "status": "pending",
                     *       "priority": "high",
                     *       "created_at": "2026-08-08T12:00:00Z",
                     *       "updated_at": "2026-08-08T12:00:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["Task"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    updateTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Server-generated task identifier (a UUIDv4 as produced by CreateTask), scoped to the authenticated caller.
                 *     A well-formed but unknown id, a well-formed id belonging to a *different* user, and a **malformed** id (not a syntactically valid UUID) all result in 404, identically. `Service.isValidID` rejects a malformed shape before either storage backend is consulted (`internal/task/service.go`), which is what makes the in-memory and PostgreSQL-backed stores agree — PostgreSQL's own `::uuid` cast would otherwise reject the value as a query error (500) rather than as "no rows", a divergence `TestPostgres_FindByID_MalformedID` still documents for a caller that reaches `Repository` directly, bypassing `Service`. The API never reveals, through the status code alone, which of the three cases applies — that is what keeps a non-owner from learning whether a given task ID exists.
                 * @example f47ac10b-58cc-4372-a567-0e02b2c3d479
                 */
                id: components["parameters"]["TaskID"];
            };
            cookie?: never;
        };
        /** @description Request bodies larger than 1 MiB are rejected (surfaces as the same 400 "invalid request body" response as malformed JSON). */
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "title": "Buy groceries and cook dinner",
                 *       "description": "Don't forget olive oil"
                 *     }
                 */
                "application/json": components["schemas"]["UpdateTaskRequest"];
            };
        };
        responses: {
            /** @description Task updated. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "f47ac10b-58cc-4372-a567-0e02b2c3d479",
                     *       "title": "Buy groceries and cook dinner",
                     *       "description": "Don't forget olive oil",
                     *       "status": "pending",
                     *       "priority": "high",
                     *       "created_at": "2026-08-08T12:00:00Z",
                     *       "updated_at": "2026-08-08T12:05:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Malformed JSON body; a missing, empty, or whitespace-only `title`; a `title`/`description` longer than 200/2000 characters (after trimming); or a non-empty `priority` that isn't one of `low`/`medium`/`high`. */
            400: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Optimistic concurrency conflict: another request updated this task between when this request's caller last read it and this write. The caller should re-fetch the task and retry. */
            409: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "task was modified concurrently, please retry"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    deleteTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Server-generated task identifier (a UUIDv4 as produced by CreateTask), scoped to the authenticated caller.
                 *     A well-formed but unknown id, a well-formed id belonging to a *different* user, and a **malformed** id (not a syntactically valid UUID) all result in 404, identically. `Service.isValidID` rejects a malformed shape before either storage backend is consulted (`internal/task/service.go`), which is what makes the in-memory and PostgreSQL-backed stores agree — PostgreSQL's own `::uuid` cast would otherwise reject the value as a query error (500) rather than as "no rows", a divergence `TestPostgres_FindByID_MalformedID` still documents for a caller that reaches `Repository` directly, bypassing `Service`. The API never reveals, through the status code alone, which of the three cases applies — that is what keeps a non-owner from learning whether a given task ID exists.
                 * @example f47ac10b-58cc-4372-a567-0e02b2c3d479
                 */
                id: components["parameters"]["TaskID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task deleted successfully. No response body. */
            204: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    transitionTaskStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Server-generated task identifier (a UUIDv4 as produced by CreateTask), scoped to the authenticated caller.
                 *     A well-formed but unknown id, a well-formed id belonging to a *different* user, and a **malformed** id (not a syntactically valid UUID) all result in 404, identically. `Service.isValidID` rejects a malformed shape before either storage backend is consulted (`internal/task/service.go`), which is what makes the in-memory and PostgreSQL-backed stores agree — PostgreSQL's own `::uuid` cast would otherwise reject the value as a query error (500) rather than as "no rows", a divergence `TestPostgres_FindByID_MalformedID` still documents for a caller that reaches `Repository` directly, bypassing `Service`. The API never reveals, through the status code alone, which of the three cases applies — that is what keeps a non-owner from learning whether a given task ID exists.
                 * @example f47ac10b-58cc-4372-a567-0e02b2c3d479
                 */
                id: components["parameters"]["TaskID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "status": "in_progress"
                 *     }
                 */
                "application/json": components["schemas"]["TransitionStatusRequest"];
            };
        };
        responses: {
            /** @description Task moved to the new status (or already was — same response shape either way). */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "f47ac10b-58cc-4372-a567-0e02b2c3d479",
                     *       "title": "Buy groceries",
                     *       "description": "Milk, eggs, bread",
                     *       "status": "in_progress",
                     *       "priority": "high",
                     *       "created_at": "2026-08-08T12:00:00Z",
                     *       "updated_at": "2026-08-08T12:05:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Malformed JSON body, or `status` is not one of the four known values. */
            400: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "invalid input: unknown status \"archived\""
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Either an optimistic concurrency conflict (see PUT /tasks/{id}'s 409), or the requested transition is not legal from the task's current status (e.g. `cancelled` → `done`) — distinguishable by the error message, both map to 409 since both mean "this request conflicts with the resource's current state." */
            409: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    completeTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Server-generated task identifier (a UUIDv4 as produced by CreateTask), scoped to the authenticated caller.
                 *     A well-formed but unknown id, a well-formed id belonging to a *different* user, and a **malformed** id (not a syntactically valid UUID) all result in 404, identically. `Service.isValidID` rejects a malformed shape before either storage backend is consulted (`internal/task/service.go`), which is what makes the in-memory and PostgreSQL-backed stores agree — PostgreSQL's own `::uuid` cast would otherwise reject the value as a query error (500) rather than as "no rows", a divergence `TestPostgres_FindByID_MalformedID` still documents for a caller that reaches `Repository` directly, bypassing `Service`. The API never reveals, through the status code alone, which of the three cases applies — that is what keeps a non-owner from learning whether a given task ID exists.
                 * @example f47ac10b-58cc-4372-a567-0e02b2c3d479
                 */
                id: components["parameters"]["TaskID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task marked as done, or already was — response shape is the same either way. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "f47ac10b-58cc-4372-a567-0e02b2c3d479",
                     *       "title": "Buy groceries",
                     *       "description": "Milk, eggs, bread",
                     *       "status": "done",
                     *       "priority": "high",
                     *       "created_at": "2026-08-08T12:00:00Z",
                     *       "updated_at": "2026-08-08T12:05:00Z"
                     *     }
                     */
                    "application/json": components["schemas"]["Task"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /**
             * @description Either the task's current status cannot legally reach `done` in one hop — only `cancelled` can't (see the Status schema's transition table); move it back to `pending` first — or an optimistic concurrency conflict: another request updated this task between when this request's caller last read it and this write, in which case the caller should re-fetch and retry.
             *     Neither is ever returned when the task is already `done`: that path is idempotent and never writes.
             */
            409: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listAttachments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Server-generated task identifier (a UUIDv4 as produced by CreateTask), scoped to the authenticated caller.
                 *     A well-formed but unknown id, a well-formed id belonging to a *different* user, and a **malformed** id (not a syntactically valid UUID) all result in 404, identically. `Service.isValidID` rejects a malformed shape before either storage backend is consulted (`internal/task/service.go`), which is what makes the in-memory and PostgreSQL-backed stores agree — PostgreSQL's own `::uuid` cast would otherwise reject the value as a query error (500) rather than as "no rows", a divergence `TestPostgres_FindByID_MalformedID` still documents for a caller that reaches `Repository` directly, bypassing `Service`. The API never reveals, through the status code alone, which of the three cases applies — that is what keeps a non-owner from learning whether a given task ID exists.
                 * @example f47ac10b-58cc-4372-a567-0e02b2c3d479
                 */
                id: components["parameters"]["TaskID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The task's attachments. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attachment"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description No such task for this user, or attachments are disabled. */
            404: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "task not found"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    uploadAttachment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Server-generated task identifier (a UUIDv4 as produced by CreateTask), scoped to the authenticated caller.
                 *     A well-formed but unknown id, a well-formed id belonging to a *different* user, and a **malformed** id (not a syntactically valid UUID) all result in 404, identically. `Service.isValidID` rejects a malformed shape before either storage backend is consulted (`internal/task/service.go`), which is what makes the in-memory and PostgreSQL-backed stores agree — PostgreSQL's own `::uuid` cast would otherwise reject the value as a query error (500) rather than as "no rows", a divergence `TestPostgres_FindByID_MalformedID` still documents for a caller that reaches `Repository` directly, bypassing `Service`. The API never reveals, through the status code alone, which of the three cases applies — that is what keeps a non-owner from learning whether a given task ID exists.
                 * @example f47ac10b-58cc-4372-a567-0e02b2c3d479
                 */
                id: components["parameters"]["TaskID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description The attachment was stored. */
            201: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Attachment"];
                };
            };
            /** @description The body was not multipart, carried no `file` part, exceeded the size limit, held a content type outside the allow-list, or the caller is already at their per-account storage quota (`ATTACHMENT_MAX_BYTES_PER_USER`) — the message never reveals another account's usage, only the caller's own. */
            400: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description No such task for this user — or attachments are disabled. As everywhere else in this API, a task belonging to another user is reported the same way a missing one is. */
            404: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "task not found"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    downloadAttachment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The attachment's `storage_key`. */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The file contents. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestID"];
                    /** @description Always `attachment`, with the original filename as a parameter. */
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description No attachment with this key for this user — covering a key that names nothing, one belonging to somebody else, a malformed (not syntactically UUID) key, or attachments being disabled entirely. All four are answered identically, the same way an unknown or foreign task id is (see the `id` path parameter on `/v1/tasks/{id}`). */
            404: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "attachment not found"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    deleteAttachment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The attachment's `storage_key`. */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Attachment deleted successfully. No response body. */
            204: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description No attachment with this key for this user — covering a key that names nothing, one belonging to somebody else, a malformed (not syntactically UUID) key, or one already deleted (by this call or an earlier one) — or attachments are disabled. */
            404: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "attachment not found"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalServerError"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getDebugVars: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current runtime statistics. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "cmdline": [
                     *         "/task-api"
                     *       ],
                     *       "memstats": {
                     *         "Alloc": 1452712,
                     *         "TotalAlloc": 1452712,
                     *         "Sys": 12802312,
                     *         "HeapObjects": 6415
                     *       }
                     *     }
                     */
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is alive. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The backing store is reachable. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description The backing store is not reachable. Distinct from the 503 an authenticated endpoint returns: this one is the readiness verdict itself, not a failed session lookup. */
            503: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestID"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "unavailable"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
